language: android
android:
  components:
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

jdk:
  - oraclejdk8

script:
  - ./gradlew clean testDevDebugUnitTest lintDevDebug jacocoTestReport coveralls -Dscan